### ISSUE TITLE
Are the returned rows sorted in any way?

### ISSUE THREAD

**Issue by pigeonburger** [fake-name/pg-spgist_hamming#10]
Not super familiar with PostgreSQL extensions, but this is pretty much exactly what I was looking for, so thank you!

Just wondering, are the returned rows sorted in any particular way? (e.g. lowest distance first?)

Right now I'm just performing a secondary check to explicitly determine the hamming distance after using this extension to narrow down potential matches, but it would be useful to know if the results are sorted, to save some more time.

Or is there some way to also return the calculated distances as part of the rows too, so I can sort by that? Not sure if you're active here anymore or not but still worth a try asking! Cheers

**Comment by pigeonburger** [comment]
Nevermind! Found the operator I needed here: https://github.com/fake-name/pg-spgist_hamming/blob/9fa70b08e0f0108de6a6673ce095c86a987d261d/bktree/bktree--1.0.sql#L81 So I can build the query I wanted!

**Comment by pigeonburger** [comment]
Nevermind, I found the operator I needed to do this by looking a bit deeper!

https://github.com/fake-name/pg-spgist_hamming/blob/9fa70b08e0f0108de6a6673ce095c86a987d261d/bktree/bktree--1.0.sql#L81-L85

So you could build a basic query like:

```
SELECT url, phash_column, phash_column <-> target_phash_int64 FROM table_name WHERE phash_column <@ (target_phash_int64, search_distance_int) ORDER BY 3;
```

to sort the returned rows.

It slightly slows down the query time (by ~0.5-1ms) but that's ok in my case. Not sure if there's a faster way but this works for me!

**Comment by fake-name** [comment]
FWIW, I don't believe the returned values will be in any particular order by default. 

I would expect them to be returned in the tree-order, which should seem effectively random from a user-perspective. Unless `sp-gist` does it's own sorting (and I can't imagine they'd do that without it being specifically requested in some way), the results will just be in the order they're found in the SP-GiST index tree.

**Comment by pigeonburger** [comment]
Yeah, that’s what I figured - I didn’t see any pattern relating to the distances so you’re probably right. On Fri, 2 Dec 2022 at 11:08 pm, C W ***@***.***> wrote:
FWIW, I don't believe the returned values will be in any particular order by default.
I would expect them to be returned in the tree-order, which should seem effectively random from a user-perspective. Unless sp-gist does it's own sorting (and I can't imagine they'd do that without it being specifically requested in some way), the results will just be in the order they're found in the SP-GiST index tree.
