### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by luckydonald** [fake-name/pg-spgist_hamming#2]
Could you provide a short example on how to install and how to use?

I stumbled across this via [stackexchange](https://dba.stackexchange.com/questions/72134/fast-hamming-distance-queries-in-postgres), but have no clue how to use it.

Cheers!

**Comment by fake-name** [comment]
I just reinstalled, so sure!

**Comment by fake-name** [comment]
Let me know if you have more questions! I think that should be a rough overview, but I'm sure I missed *something* important.

**Comment by luckydonald** [comment]
I'll try to create a docker image with it and 'll ask if I get stuck. Thanks!

**Comment by adamwilbert** [comment]
@luckydonald did you have any luck?  I'm having install issues...

**Comment by luckydonald** [comment]
I have no idea.

**Comment by luckydonald** [comment]
Turns out I indeed did work on this.

At least there is a commit referencing this issue.

>> <img width="827" alt="Screenshot 2019-11-08 at 01 23 07" src="https://user-images.githubusercontent.com/2737108/68439226-16bfa700-01c7-11ea-837c-af5b092d467b.png">




Here is what I got, I can't remember if that was working at all, but it might help you nevertheless:

```Dockerfile
FROM postgres:11.2-alpine

 ARG POSTGRES_HAMMING_VERSION=84a926fe227bbc6ad37c9fe17172b03ea9c5ff2b


 RUN set -e -x \
     && apk -U upgrade \
     && apk add --no-cache git nano curl make tree gcc libc-dev \
     && cd /tmp \
     && git clone https://github.com/fake-name/pg-spgist_hamming.git pg-spgist_hamming \
     && cd pg-spgist_hamming \
     && cd bktree \
     && make \
     && tree / \
     && rm -rf /tmp/* \
     ;    
```
@adamwilbert

**Comment by luckydonald** [comment]
@adamwilbert If you are more specific with the error, **fake-name** who offered help earlier might be able to help you.

**Comment by fake-name** [comment]
> I'm having install issues...

Please define "install issues"

> If you are more specific with the error, fake-name who offered help earlier might be able to help you.

Considering I wrote the project, I'd hope I can offer some help.
