### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by adamwilbert** [fake-name/pg-spgist_hamming#4]
Am attempting to install on Postgres 9.6

After running all steps listed and running install check this is the output of my 

make install does not appear to have any issues

```
/usr/lib/postgresql/9.6/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/9.6/bin'    --dbname=contrib_regression init utilities test_1 test_2 int8
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test init                     ... FAILED
test utilities                ... ok
test test_1                   ... ok
test test_2                   ... ok
test int8                     ... ok

======================
 1 of 5 tests failed.
======================
```

 Output of ` /home/ubuntu/pg-spgist_hamming/bktree/regression.out` Here

```
test init                     ... FAILED
test utilities                ... ok
test test_1                   ... ok
test test_2                   ... ok
test int8                     ... ok
```

**Comment by fake-name** [comment]
The testing framework is super brittle (it relies on the PSQL query output stringification). 

The later tests succeeding mean it's probably a false-failure. Can you just try creating and using the index?

**Comment by adamwilbert** [comment]
There was some other issue causing the tests to fail (postgres version mismatch with pg_config) so I started in a new container, am able to get all tests passing now, but still get 

`ERROR:  operator class "bktree_ops" does not exist for access method "spgist"` 

when attempting to add an index, which was also happening before.

Any thoughts?

**Comment by gregdan3** [comment]
You may need to do `CREATE EXTENSION bktree;` inside of psql, after your `sudo make install`

I had to for my tests

**Comment by fake-name** [comment]
`CREATE EXTENSION bktree;` Oh, gah, how did that not make it into the docs?

**Comment by fake-name** [comment]
Ok, I updated the docs. 

The make installchecks are super brittle. There has to be a better way.
