### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by mateusznajdek** [fake-name/pg-spgist_hamming#9]
Hi, have You tried maybe to install it on Windows?, I am having quite a trouble with it. When I try to "make" it I get such an error:

```
Makefile:19: Files/PostgreSQL/11/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target 'Files/PostgreSQL/11/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

```
Apparently, there is no pgxs for windows, does anyone knows how to install it, or any workaround on how to install this extension on Windows?

**Comment by ghost** [comment]
I used **chocolatey** make but I get the error too:
```
process_begin: CreateProcess(NULL, pg_config --pgxs, ...) failed.
Makefile:18: pipe: No error
make: *** No targets.  Stop.
```

**Comment by fake-name** [comment]
Yeah, the build process depends on pgxs, which explicitly doesn't support windows. I don't run postgres on windows, and completely replacing the build process would be out-of-scope. 

Maybe look at https://postgrespro.com/list/thread-id/1835275 for some pointers? It seems like doing this on windows is kind of non-trivial.
